### PR TITLE
chore: update GoReleaser to v2

### LINKED ISSUE #95: Pre-built binary for darwin/arm64 wasn't released at v0.6.44
https://github.com/container-tools/spectrum/releases/tag/v0.6.44

image

`spectrum_0.6.44_Darwin_arm64.tar.gz` wasn't released.

https://github.com/container-tools/spectrum/actions/runs/9543698903/job/26300819613#step:7:30

```
         • DEPRECATED: skipped darwin/arm64 build on Go < 1.16 for compatibility, check https://goreleaser.com/deprecations/#builds-for-darwinarm64 for more info.
```

https://goreleaser.com/deprecations/#builds-for-darwinarm64

### PR DESCRIPTION
**Pull request by suzuki-shunsuke**
- https://github.com/container-tools/spectrum/issues/95

While I looked into #95 , I found GoReleaser was very old.
To resolve #95 , I think we should upgrade GoReleaser to the latest version.
This pull request updates GoReleaser to the latest version and updates the configuration file.

## Test

I've confirmed I could build pre-built binary for darwin/arm64 and the naming style wasn't changed.

```console
$ goreleaser -v
  ____       ____      _
 / ___| ___ |  _ \ ___| | ___  __ _ ___  ___ _ __
| |  _ / _ \| |_) / _ \ |/ _ \/ _` / __|/ _ \ '__|
| |_| | (_) |  _ <  __/ |  __/ (_| \__ \  __/ |
 \____|\___/|_| \_\___|_|\___|\__,_|___/\___|_|
goreleaser: Deliver Go Binaries as fast and easily as possible
https://goreleaser.com

GitVersion:    2.0.1
GitCommit:     684c1805864e5f29acc204e34e1770eb74918d15
GitTreeState:  false
BuildDate:     2024-06-11T01:45:52Z
BuiltBy:       goreleaser
GoVersion:     go1.22.4
Compiler:      gc
ModuleSum:     h1:Wx2peRnvixEBRKxU6T0Gh+3wlire+Jv2IOW5eNPan3U=
Platform:      darwin/arm64
```

```console
$ goreleaser release --snapshot --clean
  • starting release...
  • loading                                          path=.goreleaser.yml
  • skipping announce, publish and validate...
  • loading environment variables
  • getting and validating git state
    • git state                                      commit=aae3e613c9f03b346e5d58b23d0f2291c5c309cd branch=chore-update-goreleaser current_tag=v0.6.44 previous_tag=v0.6.43 dirty=true
    • pipe skipped                                   reason=disabled during snapshot mode
  • parsing tag
  • setting defaults
  • snapshotting
    • building snapshot...                           version=v0.6.44-next
  • running before hooks
    • running                                        hook=go mod download
  • checking distribution directory
    • cleaning dist
  • setting up metadata
  • storing release metadata
    • writing                                        file=dist/metadata.json
  • loading go mod information
  • build prerequisites
  • writing effective config file
    • writing                                        config=dist/config.yaml
  • building binaries
    • building                                       binary=dist/spectrum_windows_386/spectrum.exe
    • building                                       binary=dist/spectrum_darwin_amd64_v1/spectrum
    • building                                       binary=dist/spectrum_darwin_arm64/spectrum
    • building                                       binary=dist/spectrum_linux_386/spectrum
    • building                                       binary=dist/spectrum_linux_amd64_v1/spectrum
    • building                                       binary=dist/spectrum_linux_arm64/spectrum
    • building                                       binary=dist/spectrum_windows_amd64_v1/spectrum.exe
    • building                                       binary=dist/spectrum_windows_arm64/spectrum.exe
    • took: 1s
  • archives
    • creating                                       archive=dist/spectrum_v0.6.44-next_Windows_i386.tar.gz
    • creating                                       archive=dist/spectrum_v0.6.44-next_Windows_x86_64.tar.gz
    • creating                                       archive=dist/spectrum_v0.6.44-next_Windows_arm64.tar.gz
    • creating                                       archive=dist/spectrum_v0.6.44-next_Linux_arm64.tar.gz
    • creating                                       archive=dist/spectrum_v0.6.44-next_Linux_i386.tar.gz
    • creating                                       archive=dist/spectrum_v0.6.44-next_Darwin_x86_64.tar.gz
    • creating                                       archive=dist/spectrum_v0.6.44-next_Linux_x86_64.tar.gz
    • creating                                       archive=dist/spectrum_v0.6.44-next_Darwin_arm64.tar.gz
    • took: 1s
  • calculating checksums
  • docker images
    • building docker image                          image=quay.io/container-tools/spectrum:v0.6.44
    • took: 1s
  • storing artifacts metadata
    • writing                                        file=dist/artifacts.json
  • release succeeded after 4s
  • thanks for using goreleaser!
```

```console
$ ls dist 
artifacts.json            spectrum_linux_amd64_v1                     spectrum_v0.6.44-next_Windows_arm64.tar.gz
checksums.txt             spectrum_linux_arm64                        spectrum_v0.6.44-next_Windows_i386.tar.gz
config.yaml               spectrum_v0.6.44-next_Darwin_arm64.tar.gz   spectrum_v0.6.44-next_Windows_x86_64.tar.gz
metadata.json             spectrum_v0.6.44-next_Darwin_x86_64.tar.gz  spectrum_windows_386
spectrum_darwin_amd64_v1  spectrum_v0.6.44-next_Linux_arm64.tar.gz    spectrum_windows_amd64_v1
spectrum_darwin_arm64     spectrum_v0.6.44-next_Linux_i386.tar.gz     spectrum_windows_arm64
spectrum_linux_386        spectrum_v0.6.44-next_Linux_x86_64.tar.gz
```

### CODE REVIEW

**Comment by suzuki-shunsuke** [comment]
I found the prefix `v` was added.
`spectrum_v0.6.44-next_Darwin_arm64.tar.gz` should be `spectrum_0.6.44-next_Darwin_arm64.tar.gz`.
I'm looking into how to trim `v`.

**Review by squakez — APPROVED** [review]
Thanks, lgtm. However mind that we're planning to archive this project soon. It was born as a side project for Camel K and it was deprecated over there in favour of Jib, so, likely this is the last release we're getting out.

**Comment by suzuki-shunsuke** [comment]
> I found the prefix `v` was added. `spectrum_v0.6.44-next_Darwin_arm64.tar.gz` should be `spectrum_0.6.44-next_Darwin_arm64.tar.gz`. I'm looking into how to trim `v`.

I've tested and found the prefix `v` was removed from GitHub Releases.

https://github.com/suzuki-shunsuke/spectrum/releases/tag/v0.6.45-2

So there is no problem.

**Comment by suzuki-shunsuke** [comment]
> Thanks, lgtm. However mind that we're planning to archive this project soon. It was born as a side project for Camel K and it was deprecated over there in favour of Jib, so, likely this is the last release we're getting out.

Oh, I see. Okay.
I'm a maintainer of aqua, which is a CLI version manager. https://aquaproj.github.io/
aqua supports spectrum and I found the issue #95 , so I handled the issue.

**Comment by squakez** [comment]
Let me know if this is good to merge now.

**Comment by suzuki-shunsuke** [comment]
Please merge at your timing.
This pull request is already ready.

**Pull request merged**
